# -*- coding: utf-8 -*-
"""4_텔레그램봇_웹크롤링_오늘급식.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1NSJG_Dh38bSCf9r8gR4i3XFeLhHipW
"""

# 웹크롤링 라이브러리 설치 
!pip install requests
!pip install bs4

# 챗봇 라이브러리 설치 
!pip install python-telegram-bot

import requests
from bs4 import BeautifulSoup
import datetime
import re

import telegram

######## 1. 오늘 날짜 정보 ########
now = str(datetime.datetime.now())
#print('now :', now)
day = now[0:10].replace('-', '.')
print('오늘의 메뉴 :',day)

######## 2. 오늘의 급식 메뉴 조회 ########
req = requests.get("https://stu.sen.go.kr/sts_sci_md01_001.do?schulCode=B100000420&schulCrseScCode=4&schulKndScCode=04&schMmealScCode=2&schYmd="+day)
#print(req.text)
soup = BeautifulSoup(req.text, "html.parser")
#print(soup)
element = soup.find_all("tr")
#print(element[0])
day_info = element[0].find_all('th', {'scope' :'col'})

i = 0
for date in day_info:
    if(re.match(day, date.text)):
        print(date.text)
        break
    i= i+1

#print(i)
element = element[2].find_all('td')
#print(element)

element = element[i] 
element = str(element)
#print(element)
element = element.replace('[', '')
element = element.replace(']', '')
element = element.replace('<br/>', '\n')
element = element.replace('<td class="textC last">', '')
element = element.replace('<td class="textC">', '')
element = element.replace('</td>', '')
element = element.replace('(h)', '')
element = element.replace('.', '')
element = re.sub(r"\d", "", element)

print(element)

######## 3. 조회한 급식 메뉴를 챗봇이 전송하기 ########
# 봇 토큰, userid 
my_token = "아까 발급받은 API(토큰)을 입력"
bot = telegram.Bot(token=my_token)
Id = 111111111 #user Id

#봇이 나에게 전송하는 메세지 
bot.sendMessage(chat_id = Id, text = "안녕~")

#식단 정보보내기
bot.sendMessage(chat_id = Id, text = '오늘의 메뉴 :')
bot.sendMessage(chat_id = Id, text = day)
bot.sendMessage(chat_id = Id, text = element)